spring:
  datasource:
    url: jdbc:h2:~/template;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false